COUNTRY_CURRENCY_MAP = {
    "afghanistan": "AFN",
    "albania": "ALL",
    "algeria": "DZD",
    "angola": "AOA",
    "argentina": "ARS",
    "armenia": "AMD",
    "australia": "AUD",
    "austria": "EUR",
    "azerbaijan": "AZN",

    "bahrain": "BHD",
    "bangladesh": "BDT",
    "belarus": "BYN",
    "belgium": "EUR",
    "belize": "BZD",
    "benin": "XOF",
    "bhutan": "BTN",
    "bolivia": "BOB",
    "bosnia and herzegovina": "BAM",
    "botswana": "BWP",
    "brazil": "BRL",
    "brunei": "BND",
    "bulgaria": "BGN",
    "burkina faso": "XOF",
    "burundi": "BIF",

    "cambodia": "KHR",
    "cameroon": "XAF",
    "canada": "CAD",
    "chad": "XAF",
    "chile": "CLP",
    "china": "CNY",
    "colombia": "COP",
    "congo": "XAF",
    "costa rica": "CRC",
    "croatia": "EUR",
    "cuba": "CUP",
    "cyprus": "EUR",
    "czech republic": "CZK",

    "denmark": "DKK",
    "dominican republic": "DOP",

    "ecuador": "USD",
    "egypt": "EGP",
    "el salvador": "USD",
    "estonia": "EUR",
    "ethiopia": "ETB",

    "fiji": "FJD",
    "finland": "EUR",
    "france": "EUR",

    "gabon": "XAF",
    "georgia": "GEL",
    "germany": "EUR",
    "ghana": "GHS",
    "greece": "EUR",
    "guatemala": "GTQ",
    "guinea": "GNF",

    "haiti": "HTG",
    "honduras": "HNL",
    "hong kong": "HKD",
    "hungary": "HUF",

    "iceland": "ISK",
    "india": "INR",
    "indonesia": "IDR",
    "iran": "IRR",
    "iraq": "IQD",
    "ireland": "EUR",
    "israel": "ILS",
    "italy": "EUR",

    "jamaica": "JMD",
    "japan": "JPY",
    "jordan": "JOD",

    "kazakhstan": "KZT",
    "kenya": "KES",
    "kuwait": "KWD",
    "kyrgyzstan": "KGS",

    "laos": "LAK",
    "latvia": "EUR",
    "lebanon": "LBP",
    "libya": "LYD",
    "lithuania": "EUR",
    "luxembourg": "EUR",

    "macau": "MOP",
    "madagascar": "MGA",
    "malawi": "MWK",
    "malaysia": "MYR",
    "maldives": "MVR",
    "mali": "XOF",
    "malta": "EUR",
    "mexico": "MXN",
    "moldova": "MDL",
    "mongolia": "MNT",
    "morocco": "MAD",
    "mozambique": "MZN",
    "myanmar": "MMK",

    "namibia": "NAD",
    "nepal": "NPR",
    "netherlands": "EUR",
    "new zealand": "NZD",
    "nicaragua": "NIO",
    "nigeria": "NGN",
    "north korea": "KPW",
    "norway": "NOK",

    "oman": "OMR",

    "pakistan": "PKR",
    "panama": "PAB",
    "papua new guinea": "PGK",
    "paraguay": "PYG",
    "peru": "PEN",
    "philippines": "PHP",
    "poland": "PLN",
    "portugal": "EUR",

    "qatar": "QAR",

    "romania": "RON",
    "russia": "RUB",
    "rwanda": "RWF",

    "saudi arabia": "SAR",
    "senegal": "XOF",
    "serbia": "RSD",
    "singapore": "SGD",
    "slovakia": "EUR",
    "slovenia": "EUR",
    "somalia": "SOS",
    "south africa": "ZAR",
    "south korea": "KRW",
    "spain": "EUR",
    "sri lanka": "LKR",
    "sudan": "SDG",
    "sweden": "SEK",
    "switzerland": "CHF",
    "syria": "SYP",

    "taiwan": "TWD",
    "tajikistan": "TJS",
    "tanzania": "TZS",
    "thailand": "THB",
    "tunisia": "TND",
    "turkey": "TRY",
    "turkmenistan": "TMT",

    "uganda": "UGX",
    "ukraine": "UAH",
    "united arab emirates": "AED",
    "united kingdom": "GBP",
    "united states": "USD",
    "uruguay": "UYU",
    "uzbekistan": "UZS",

    "venezuela": "VES",
    "vietnam": "VND",

    "yemen": "YER",

    "zambia": "ZMW",
    "zimbabwe": "ZWL",
}
